11-binary_to_decimal

diff --git a/0x03-shell_variables_expansions/11-binary_to_decimal b/0x03-shell_variables_expansions/11-binary_to_decimal
--- a/0x03-shell_variables_expansions/11-binary_to_decimal
+++ b/0x03-shell_variables_expansions/11-binary_to_decimal
@@ -1,2 +1,12 @@
 #!/bin/bash
-echo $((2#BINARY)0)
+
+# Check if the BINARY environment variable is set
+if [ -z "$BINARY" ]; then
+  echo "Error: The BINARY environment variable is not set."
+  exit 1
+fi
+
+# Convert the binary number to decimal and display it
+decimal=$((2#$BINARY))
+echo $decimal
+
